In [68]:
text = "the cat sat in the"
context = "cat,on"
target = "sat"

In [69]:
import numpy as np
vcat = np.array([[0.00,1.00,0.00,0.00,0.00]])
von = np.array([[0.00,0.00,0.00,1.00,0.00]])
vcat.shape,von.shape

((1, 5), (1, 5))

In [70]:
x = vcat+von

x.shape,x

((1, 5), array([[0., 1., 0., 1., 0.]]))

In [71]:
w1 = np.array([[0.10,0.80,-0.30],
             [0.90,-0.20,0.10],
             [-0.50,0.40,0.60],
             [-0.20,0.70,-0.5],
             [0.2,0.8,-0.2]])

w1.shape

(5, 3)

In [72]:
h = np.dot(x,w1)
h

array([[ 0.7,  0.5, -0.4]])

In [73]:
w2  = np.array([[0.40,-0.10,0.70,0.20,0.30],
             [-0.20,0.30,-0.3,0.6,-0.4],           
             [0.1,0.5,-0.2,0.1,0.8]])

w2.shape

(3, 5)

In [74]:
z = np.dot(h,w2)
z

array([[ 0.14, -0.12,  0.42,  0.4 , -0.31]])

In [75]:
import torch

y_pred = torch.from_numpy(np.array(z))
print(type(y_pred))
y_pred = torch.nn.functional.softmax(y_pred)
y_pred

<class 'torch.Tensor'>


C:\Users\Parthiban\AppData\Local\Temp\ipykernel_10988\2593924333.py:5: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  y_pred = torch.nn.functional.softmax(y_pred)


tensor([[0.1989, 0.1533, 0.2631, 0.2579, 0.1268]], dtype=torch.float64)

In [76]:
target = np.array([0,0,1,0,0])
target


array([0, 0, 1, 0, 0])

In [77]:
y_pred = np.array(y_pred)
y_pred

array([[0.19885698, 0.15332899, 0.2631136 , 0.25790361, 0.12679681]])

In [78]:
def cross_entropy_loss(y_true, y_pred):
    return -np.sum(y_true * np.log(y_pred ))

print(cross_entropy_loss(target,y_pred))

1.3351693834154168


In [79]:
dz = y_pred-target
dz

array([[ 0.19885698,  0.15332899, -0.7368864 ,  0.25790361,  0.12679681]])

In [80]:
dw2  = np.dot(np.transpose(h),dz)
dw2

array([[ 0.13919989,  0.1073303 , -0.51582048,  0.18053252,  0.08875777],
       [ 0.09942849,  0.0766645 , -0.3684432 ,  0.1289518 ,  0.06339841],
       [-0.07954279, -0.0613316 ,  0.29475456, -0.10316144, -0.05071872]])

In [81]:
dh = np.dot(dz,np.transpose(w2))
dh

array([[-0.36199082,  0.33131666,  0.37115528]])

In [82]:
dw1 = np.dot(np.transpose(x),dh)
dw1

array([[-0.        ,  0.        ,  0.        ],
       [-0.36199082,  0.33131666,  0.37115528],
       [-0.        ,  0.        ,  0.        ],
       [-0.36199082,  0.33131666,  0.37115528],
       [-0.        ,  0.        ,  0.        ]])

In [83]:
w2 = w2 - (0.05*dw2)
w2

array([[ 0.39304001, -0.10536651,  0.72579102,  0.19097337,  0.29556211],
       [-0.20497142,  0.29616678, -0.28157784,  0.59355241, -0.40316992],
       [ 0.10397714,  0.50306658, -0.21473773,  0.10515807,  0.80253594]])

In [84]:
w1 = w1 - (0.05*dw1)
w1

array([[ 0.1       ,  0.8       , -0.3       ],
       [ 0.91809954, -0.21656583,  0.08144224],
       [-0.5       ,  0.4       ,  0.6       ],
       [-0.18190046,  0.68343417, -0.51855776],
       [ 0.2       ,  0.8       , -0.2       ]])