In [5]:
import numpy as np


x = np.array([[1,1],
            [1.5,2],
            [2,2],
            [2.5,3],
            [3,4]])

w = np.array([
    [10],[2]
])

b = np.array([[2]])

x.shape,w.shape,b.shape

((5, 2), (2, 1), (1, 1))

In [6]:
y_pred = np.dot(x,w)+b
y_pred

array([[14.],
       [21.],
       [26.],
       [33.],
       [40.]])

In [7]:
y = np.array([[15],
                [22.5],
                [27],
                [35],
                [45]])

y.shape

(5, 1)

In [8]:
loss = np.mean((y-y_pred)**2)
loss

6.65

In [10]:
dw = 2/5 * np.dot(np.transpose(x),(y_pred-y))
dw

array([[-10.1],
       [-12.8]])

In [12]:
alpha = 0.01
w =w - alpha*dw
w

array([[10.101],
       [ 2.128]])

In [13]:
db = 2/5* np.sum(y_pred-y)
db

-4.2

In [14]:
b = b - alpha*db
b

array([[2.042]])