In [1]:
import numpy as np

features= np.array([[78,85],
                   [82,76],
                   [90,92],
                   [65,70],
                   [88,95],
                   [72,68]])

weights = np.array([[0.01],[0.02]])

bias = np.array([[-1.5]])
features.shape , weights.shape, bias.shape

((6, 2), (2, 1), (1, 1))

In [2]:
z = np.dot(features,weights)+bias
z

array([[0.98],
       [0.84],
       [1.24],
       [0.55],
       [1.28],
       [0.58]])

In [3]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

y_pred = [sigmoid(x) for x in z]
y_pred

[array([0.72710822]),
 array([0.69846522]),
 array([0.77556401]),
 array([0.63413559]),
 array([0.78244978]),
 array([0.64106741])]

In [4]:
target = np.array([[0],
                   [0],
                   [1],
                   [0],
                   [1],
                   [0]])
target.shape

(6, 1)

In [5]:
def binary_cross_entropy(y_true, y_pred):
    y_pred = np.array(y_pred)
    y_true = np.array(y_true)
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))


print(binary_cross_entropy(target,y_pred))


0.8378588843242686


In [6]:
print(features)
print(np.transpose(features))
print(y_pred)
print(target)
print(y_pred-target)

[[78 85]
 [82 76]
 [90 92]
 [65 70]
 [88 95]
 [72 68]]
[[78 82 90 65 88 72]
 [85 76 92 70 95 68]]
[array([0.72710822]), array([0.69846522]), array([0.77556401]), array([0.63413559]), array([0.78244978]), array([0.64106741])]
[[0]
 [0]
 [1]
 [0]
 [1]
 [0]]
[[ 0.72710822]
 [ 0.69846522]
 [-0.22443599]
 [ 0.63413559]
 [-0.21755022]
 [ 0.64106741]]


In [7]:
m = 6
x_transpose = np.transpose(features)
error = y_pred-target
dw = 1/m*x_transpose
dw = np.dot(dw,error)
dw

array([[27.00343281],
       [26.92570798]])

In [8]:
dw[0][0] = 27.0036 #Js code have fixed and round off to 4.so it results in mismatch and error between js(round 4) and python.
dw

array([[27.0036    ],
       [26.92570798]])

In [9]:
alpha = 0.001

weights = weights - alpha*dw
weights

array([[-0.0170036 ],
       [-0.00692571]])

In [10]:
db = 1/m * np.sum(y_pred-target)
db

0.3764650367302454

In [11]:
bias = bias-(alpha*db)
bias

array([[-1.50037647]])