In [1]:
import numpy as np

features= np.array([[78,85],
                   [82,76],
                   [90,92],
                   [65,70],
                   [88,95],[72,68]])

weights = np.array([[0.01],[0.02]])

bias = np.array([[-1.50]])
features.shape , weights.shape, bias.shape

((6, 2), (2, 1), (1, 1))

In [2]:
z = np.dot(features,weights)+bias
z

array([[0.98],
       [0.84],
       [1.24],
       [0.55],
       [1.28],
       [0.58]])

In [3]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

y_pred = [sigmoid(x) for x in z]
y_pred

[array([0.72710822]),
 array([0.69846522]),
 array([0.77556401]),
 array([0.63413559]),
 array([0.78244978]),
 array([0.64106741])]

In [4]:
target = np.array([[0],
                   [0],
                   [1],
                   [0],
                   [1],
                   [1]])
target.shape

(6, 1)

In [5]:
def binary_cross_entropy(y_true, y_pred):
    y_pred = np.array(y_pred)
    y_true = np.array(y_true)
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))


print(binary_cross_entropy(target,y_pred))


0.7411922176576019
