In [83]:
import torch
import torch.nn.functional as F

In [84]:
x = torch.tensor([
    [0.8,-0.2,0.5,1.2]
])

router_weights = torch.tensor([
    [1.2,-0.5,0.8,0.3,-1.5,0.6,0.9,-0.1],
    [-0.9,1.8,-0.2,1.10,0.4,-1.2,0.3,0.7],
    [0.4,0.7,1.5,-0.8,0.9,0.1,-1.10,0.5],
    [0.6,-1.10,0.4,1.30,-0.7,1.4,0.2,-0.9]
])

print(x.shape)
print(router_weights.shape)

torch.Size([1, 4])
torch.Size([4, 8])


In [85]:
logits = x @ router_weights
logits

tensor([[ 2.0600, -1.7300,  1.9100,  1.1800, -1.6700,  2.4500,  0.3500, -1.0500]])

In [86]:
expert_1 = torch.tensor([[0.1,0.2,0.3,0.4]])
expert_6 = torch.tensor([[2.1,2.2,2.3,2.4]])
print(expert_1.shape)
print(expert_6.shape)

torch.Size([1, 4])
torch.Size([1, 4])


In [87]:
topk_vals, topk_idx = torch.topk(logits,2,dim=-1)
print(topk_vals,topk_idx)

tensor([[2.4500, 2.0600]]) tensor([[5, 0]])


In [88]:
gate_weights = F.softmax(topk_vals,dim=-1)
gate_weights

tensor([[0.5963, 0.4037]])

In [89]:
output = expert_1*gate_weights[0][1]+expert_6*gate_weights[0][0]
output

tensor([[1.2926, 1.3926, 1.4926, 1.5926]])