In [8]:
import numpy as np

x = np.array([0.8,-0.3,0.5,1.2])
w_a = np.array([[0.5,-0.2],[0.8,0.1],[-0.7,0.4],[0.2,0.9]])
w_b = np.array([[0.9,-0.4],[-0.1,0.6],[0.3,-0.8],[0.7,0.2]])

print(x.shape)
print(w_a.shape)
print(w_b.shape)

(4,)
(4, 2)
(4, 2)


In [9]:
a = np.dot(x,w_a)
a

array([0.05, 1.09])

In [10]:
b = np.dot(x,w_b)
b

array([ 1.74, -0.66])

In [11]:
def sigmoid(x):
    return 1 / (1+ np.exp(-x))

gate = sigmoid(b)
gate

array([0.85068707, 0.34073961])

In [13]:
output = []
for a_val,gate_val in zip(a,gate):
    output.append(a_val*gate_val)
output

[0.042534353273457864, 0.3714061765879898]