In [11]:
import numpy as np

x = np.array([[0.8,-0.3,0.5,1.2]])
w_a = np.array([[0.5,-0.2],
                [0.8,0.1],
                [-0.7,0.4],
                [0.2,0.9]
                ])
w_b = np.array([
    [2.5,-3.0],
    [-0.1,0.2],
    [0.3,-0.5],
    [1.0,0.8]
])
print(x.shape)
print(w_a.shape)
print(w_b.shape)

(1, 4)
(4, 2)
(4, 2)


In [12]:
a = np.dot(x,w_a)
a

array([[0.05, 1.09]])

In [13]:
b = np.dot(x,w_b)
b

array([[ 3.38, -1.75]])

In [22]:
def sigmoid(x):
    return 1 / (1+ np.exp(-x))
sigmoid_b = sigmoid(b)
sigmoid_b

array([[0.96707361, 0.1480472 ]])

In [25]:
swish = []
for b_val,sig_val in zip(b,sigmoid_b):
    swish.append(b_val*sig_val)
print(swish)


[array([ 3.26870879, -0.2590826 ])]


In [26]:
output = []
for a_val,swish_val in zip(a,swish):
    output.append(a_val*swish_val)
print(output)

[array([ 0.16343544, -0.28240003])]
