In [1]:
import numpy as np

image = np.array([[10,10,10,0,0],
                  [10,10,10,0,0],
                  [10,10,10,0,0],
                  [0,0,0,0,0],
                  [0,0,0,0,0]])

image.shape

(5, 5)

In [2]:
kernel = np.array([[1,0,-1],
                   [1,0,-1],
                   [1,0,-1]])
kernel.shape

(3, 3)

In [4]:
first = np.array([
    [10,10,10],
    [10,10,10],
    [10,10,10],
])

res = np.dot(first,kernel)

In [5]:
res

array([[ 30,   0, -30],
       [ 30,   0, -30],
       [ 30,   0, -30]])

In [ ]:
image_height, image_width = image.shape
kernel_height, kernel_width = kernel.shape

# Calculate output dimensions
output_height = image_height - kernel_height + 1
output_width = image_width - kernel_width + 1

output = np.zeros((output_height, output_width))

for i in range(output_height):
    for j in range(output_width):
        region = image[i:i+kernel_height, j:j+kernel_width]
        output[i, j] = np.sum(region * kernel)


In [7]:
output

array([[ 0., 30., 30.],
       [ 0., 20., 20.],
       [ 0., 10., 10.]])

In [ ]:
# output = max(0,input)

TypeError: '>' not supported between instances of 'method' and 'int'

In [18]:
input_height = output.shape[0]
input_width = output.shape[1]
print(input_height,input_width)
max_pool = np.zeros((2,2))
for i in range(input_height-1):
    for j in range(input_width-1):
        region = output[i:i+2,j:j+2]
        max_pool[i,j] = np.max(region)
max_pool
        

3 3


array([[30., 30.],
       [20., 20.]])

In [29]:
flatten_image = np.matrix.flatten(max_pool)
flatten_image = np.array([flatten_image])
flatten_image.shape

(1, 4)

In [36]:
weights = np.array([[0.5],[-0.5],[0.2],[-0.2]])
bias = 0.1
weights.shape

(4, 1)

In [37]:
output = np.dot(flatten_image,weights) + bias
output

array([[0.1]])