In [35]:
import numpy as np

In [36]:
a0 = np.array([[0.5,-0.2]])
w1 = np.array([[0.1,0.4,-0.2,0.7],
              [0.3,-0.5,0.6,-0.10]])
b1 = np.array([[0.1,0.2,0.1,-0.3]])
a0.shape,w1.shape,b1.shape

((1, 2), (2, 4), (1, 4))

In [37]:
z1  = np.dot(a0,w1)+b1
z1

array([[ 0.09,  0.5 , -0.12,  0.07]])

In [38]:
w2 = np.array([[0.4,-0.2,0.1,0.5],
               [-0.1,0.3,-0.5,0.2],
               [0.7,-0.3,0.2,-0.1],
               [0.2,0.6,-0.4,0.3]])
w2.shape

(4, 4)

In [39]:
import torch

def relu(y):
    y = torch.from_numpy(y)
    return torch.nn.functional.relu(y)

a1 = relu(z1)

In [40]:
print(a1)

b2 = np.array([[-0.2,0.1,0.3,-0.1]])
b2.shape

tensor([[0.0900, 0.5000, 0.0000, 0.0700]], dtype=torch.float64)


(1, 4)

In [41]:
z2 = np.dot(a1,w2)+b2
z2

array([[-0.2  ,  0.274,  0.031,  0.066]])

In [42]:
a2 = relu(z2)
a2

tensor([[0.0000, 0.2740, 0.0310, 0.0660]], dtype=torch.float64)

In [43]:
w3 = np.array([[0.2,-0.1],
               [-0.3,0.5],
               [0.6,-0.2],
               [-0.1,0.4]])

b3 = np.array([[0.1,-0.2]])
w3.shape,b3.shape

((4, 2), (1, 2))

In [44]:
z3 = np.dot(a2,w3)+b3
z3

array([[ 0.0298, -0.0428]])

In [45]:
def softmax(y):
    y = torch.from_numpy(y)
    return torch.nn.functional.softmax(y)

In [46]:
a3 = softmax(z3)
a3.shape,a3

C:\Users\Parthiban\AppData\Local\Temp\ipykernel_11540\458418228.py:3: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return torch.nn.functional.softmax(y)


(torch.Size([1, 2]), tensor([[0.5181, 0.4819]], dtype=torch.float64))

In [47]:
y = np.array([[0.00,1]])
y.shape

(1, 2)

In [59]:
y = torch.tensor(y)
print(y.shape)
print(a3.shape)
import torch.nn as nn
loss = nn.CrossEntropyLoss()

print(loss(y,a3))

torch.Size([1, 2])
torch.Size([1, 2])
tensor(0.8314, dtype=torch.float64)


C:\Users\Parthiban\AppData\Local\Temp\ipykernel_11540\1943651765.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(y)


In [62]:
def cross_entropy_loss(pred, target):
   
    pred = torch.tensor(pred)
    loss = -torch.sum(target * torch.log(pred)) / pred.shape[0]
    return loss

l = cross_entropy_loss(a3, y)
print(l)

tensor(0.7301, dtype=torch.float64)


C:\Users\Parthiban\AppData\Local\Temp\ipykernel_11540\3520367850.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  pred = torch.tensor(pred)


In [63]:
dz3 = a3-y
dz3

tensor([[ 0.5181, -0.5181]], dtype=torch.float64)

In [64]:
dw3 = np.dot(np.transpose(a2),dz3)
dw3

array([[ 0.        , -0.        ],
       [ 0.14197092, -0.14197092],
       [ 0.0160624 , -0.0160624 ],
       [ 0.03419737, -0.03419737]])

In [73]:
z2 = np.array(z2)
dz3 = np.array(dz3)
w3 = np.array(w3)

In [ ]:
def relu_derivative(x):
    return (x > 0).astype(float)
   

In [79]:
dz2 = (np.dot(dz3,np.transpose(w3)))*relu_derivative(z2)
dz2

array([[ 0.        , -0.41451363,  0.41451363, -0.25907102]])

In [75]:
db3 = dz3
db3

array([[ 0.51814203, -0.51814203]])

In [80]:
dw2 = np.dot(np.transpose(a1),dz2)
dw2

array([[ 0.        , -0.03730623,  0.03730623, -0.02331639],
       [ 0.        , -0.20725681,  0.20725681, -0.12953551],
       [ 0.        , -0.        ,  0.        , -0.        ],
       [ 0.        , -0.02901595,  0.02901595, -0.01813497]])

In [83]:
dz1 = np.dot(dz2,np.transpose(w2))*relu_derivative(z1)
dz1

array([[-0.00518142, -0.3834251 ,  0.        , -0.49223493]])

In [86]:
db2 = dz2
db2

array([[ 0.        , -0.41451363,  0.41451363, -0.25907102]])

In [87]:
dw1 = np.dot(np.transpose(a0),dz1)
dw1

array([[-0.00259071, -0.19171255,  0.        , -0.24611747],
       [ 0.00103628,  0.07668502, -0.        ,  0.09844699]])

In [88]:
db1 = dz1
db1

array([[-0.00518142, -0.3834251 ,  0.        , -0.49223493]])