Recurrent Neural Network(RNN)

In [63]:
import torch
import torch.nn.functional as F

x1 = torch.tensor([
    [1,0]
],dtype=float, requires_grad=True)
w_xh = torch.tensor([
    [0.5,-0.2,0.8,0.1],
    [0.3,0.6,-0.4,0.9],
],dtype=float, requires_grad=True)
w_hh = torch.tensor([
    [0.2,0.5,-0.3,0.4],
    [-0.1,0.7,0.6,-0.2],
    [0.8,-0.4,0.1,0.9],
    [0.3,-0.1,0.5,0.7],
],dtype=float,requires_grad=True)

b_h = torch.tensor([
    [0.1,0.1,0.1,0.1]
],dtype=float, requires_grad=True)
h0 = torch.tensor([
    [0,0,0,0]
],dtype=float, requires_grad=True)

x1.shape , w_xh.shape ,w_hh.shape, b_h.shape , h0.shape , 


(torch.Size([1, 2]),
 torch.Size([2, 4]),
 torch.Size([4, 4]),
 torch.Size([1, 4]),
 torch.Size([1, 4]))

In [64]:
h1 = F.tanh(x1@w_xh + h0@w_hh + b_h)
h1

tensor([[ 0.5370, -0.0997,  0.7163,  0.1974]], dtype=torch.float64,
       grad_fn=<TanhBackward0>)

In [65]:
w_hy = torch.tensor([[0.6,-0.3],
                    [-0.2,0.8],
                    [0.9,-0.1],
                    [0.3,0.7]],dtype =float)
b_y = torch.tensor([[0.1,0.1]],dtype=float)

w_hy.shape,b_y.shape

(torch.Size([4, 2]), torch.Size([1, 2]))

In [66]:
y1 = h1@w_hy+b_y
y1

tensor([[ 1.1460, -0.0743]], dtype=torch.float64, grad_fn=<AddBackward0>)

In [67]:
y1_pred = F.softmax(y1)
y1_pred

C:\Users\Parthiban\AppData\Local\Temp\ipykernel_20544\2366193953.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  y1_pred = F.softmax(y1)


tensor([[0.7721, 0.2279]], dtype=torch.float64, grad_fn=<SoftmaxBackward0>)

In [68]:

x2 = torch.tensor([
    [0,1]
],dtype=float)
#t2
w_xh = torch.tensor([
    [0.5,-0.2,0.8,0.1],
    [0.3,0.6,-0.4,0.9],
],dtype=float)

w_hh = torch.tensor([
    [0.2,0.5,-0.3,0.4],
    [-0.1,0.7,0.6,-0.2],
    [0.8,-0.4,0.1,0.9],
    [0.3,-0.1,0.5,0.7],
],dtype=float)

b_h = torch.tensor([
    [0.1,0.1,0.1,0.1]
],dtype=float)

x1.shape , w_xh.shape ,w_hh.shape, b_h.shape 


(torch.Size([1, 2]),
 torch.Size([2, 4]),
 torch.Size([4, 4]),
 torch.Size([1, 4]))

In [69]:
h2  = F.tanh(x2@w_xh+h1@w_hh+b_h)
h2

tensor([[ 0.8176,  0.5317, -0.3369,  0.9652]], dtype=torch.float64,
       grad_fn=<TanhBackward0>)

In [70]:
#t2
w_hy = torch.tensor([[0.6,-0.3],
                    [-0.2,0.8],
                    [0.9,-0.1],
                    [0.3,0.7]],dtype =float)
b_y = torch.tensor([[0.1,0.1]],dtype=float)

w_hy.shape,b_y.shape

(torch.Size([4, 2]), torch.Size([1, 2]))

In [71]:
y2 = h2@w_hy+b_y
y2

tensor([[0.4706, 0.9894]], dtype=torch.float64, grad_fn=<AddBackward0>)

In [72]:
y2_pred = F.softmax(y2)
y2_pred

C:\Users\Parthiban\AppData\Local\Temp\ipykernel_20544\3722561250.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  y2_pred = F.softmax(y2)


tensor([[0.3731, 0.6269]], dtype=torch.float64, grad_fn=<SoftmaxBackward0>)

In [73]:
t1 = torch.tensor([
    [0.0,1.0]
],dtype=float)
t2 = torch.tensor([
    [1.0,0.0]
],dtype=float)
t1.shape,t2.shape

(torch.Size([1, 2]), torch.Size([1, 2]))

In [74]:
ll1 = torch.nn.functional.cross_entropy(y1_pred, t1.argmax(dim=1))
ll2 = torch.nn.functional.cross_entropy(y2_pred, t2.argmax(dim=1))
l1 = - torch.log(y1_pred)*t1 
l2 = - torch.log(y2_pred)*t2
l1,l2,ll1,ll2

(tensor([[0.0000, 1.4790]], dtype=torch.float64, grad_fn=<MulBackward0>),
 tensor([[0.9858, 0.0000]], dtype=torch.float64, grad_fn=<MulBackward0>),
 tensor(1.0019, dtype=torch.float64, grad_fn=<NllLossBackward0>),
 tensor(0.8280, dtype=torch.float64, grad_fn=<NllLossBackward0>))

In [75]:
1.4790+0.9858

2.4648000000000003

In [76]:
dl_dy1_pred = y1_pred-t1
dl_dy1_pred 


tensor([[ 0.7721, -0.7721]], dtype=torch.float64, grad_fn=<SubBackward0>)

In [77]:
dl_dy2_pred = y2_pred-t2
dl_dy2_pred


tensor([[-0.6269,  0.6269]], dtype=torch.float64, grad_fn=<SubBackward0>)

In [78]:
dl_dy1 = dl_dy1_pred
dl_dy2 = dl_dy2_pred
dl_dy1,dl_dy2

(tensor([[ 0.7721, -0.7721]], dtype=torch.float64, grad_fn=<SubBackward0>),
 tensor([[-0.6269,  0.6269]], dtype=torch.float64, grad_fn=<SubBackward0>))

In [79]:
dl_dh2 = dl_dy2@w_hy.T
dl_dh2

tensor([[-0.5642,  0.6269, -0.6269,  0.2507]], dtype=torch.float64,
       grad_fn=<MmBackward0>)

In [80]:
import numpy as np

dh2_dz2 = 1 - h2 ** 2  
jacobian = torch.diag(dh2_dz2[0]) @ w_hh  
jacobian

tensor([[ 0.0663,  0.1657, -0.0994,  0.1326],
        [-0.0717,  0.5021,  0.4304, -0.1435],
        [ 0.7092, -0.3546,  0.0886,  0.7978],
        [ 0.0205, -0.0068,  0.0341,  0.0478]], dtype=torch.float64,
       grad_fn=<MmBackward0>)

In [81]:
dl_dh1 = ( dl_dy1@w_hy.T) + (dl_dh2@jacobian)
dl_dh1 

tensor([[ 0.1731, -0.3303,  1.0510, -0.9618]], dtype=torch.float64,
       grad_fn=<AddBackward0>)

In [82]:
# Derivative of tanh at h2
dh2_dpreact = 1 - h2 ** 2

# Backprop through h2
dl_dh2_through_h1 = (dl_dh2 * dh2_dpreact) @ w_hh.T

# Total dl_dh1
dl_dh1 = (dl_dy1 @ w_hy.T) + dl_dh2_through_h1


In [83]:
dl_dh1

tensor([[ 1.0559, -0.7755,  0.4025, -0.6758]], dtype=torch.float64,
       grad_fn=<AddBackward0>)

In [84]:
dl_db_y = dl_dy1+dl_dy2
dl_db_y

tensor([[ 0.1453, -0.1453]], dtype=torch.float64, grad_fn=<AddBackward0>)

In [ ]:
dl_dw_hy = h1.T@dl_dy1+ h2.T@dl_dy2
dl_dw_hy

tensor([[-0.0979,  0.0979],
        [-0.4103,  0.4103],
        [ 0.7643, -0.7643],
        [-0.4527,  0.4527]], dtype=torch.float64, grad_fn=<AddBackward0>)

In [88]:
dl_dw_xh = x1.T @(dl_dh1*1 - h1**2) + x2.T@(dl_dh2*1 - h2**2)
dl_dw_xh

tensor([[ 0.7675, -0.7855, -0.1106, -0.7148],
        [-1.2327,  0.3442, -0.7404, -0.6810]], dtype=torch.float64,
       grad_fn=<AddBackward0>)

In [89]:
dl_dw_xh = x1.T @ (dl_dh1 * (1 - h1 ** 2)) + x2.T @ (dl_dh2 * (1 - h2 ** 2))


In [90]:
dl_dw_xh

tensor([[ 0.7514, -0.7678,  0.1960, -0.6495],
        [-0.1870,  0.4497, -0.5557,  0.0171]], dtype=torch.float64,
       grad_fn=<AddBackward0>)

In [91]:
dl_dw_hh =  h0.T @ (dl_dh1 * (1 - h1 ** 2)) + h1.T @ (dl_dh2 * (1 - h2 ** 2))
dl_dw_hh

tensor([[-0.1004,  0.2415, -0.2984,  0.0092],
        [ 0.0186, -0.0448,  0.0554, -0.0017],
        [-0.1340,  0.3221, -0.3981,  0.0123],
        [-0.0369,  0.0888, -0.1097,  0.0034]], dtype=torch.float64,
       grad_fn=<AddBackward0>)

In [92]:
dl_db_h = (dl_dh1 * (1 - h1 ** 2)) + (dl_dh2 * (1 - h2 ** 2))
dl_db_h

tensor([[ 0.5643, -0.3182, -0.3597, -0.6323]], dtype=torch.float64,
       grad_fn=<AddBackward0>)