In [30]:
import torch

input_embeddings = torch.tensor([[1,0,0,0,0,0,0,0],
                         [0,1,0,0,0,0,0,0],
                         [0,0,1,0,0,0,0,0],
                         [0,0,0,1,0,0,0,0],
                         [0,0,0,0,1,0,0,0]],dtype=torch.float32)


wq = torch.tensor([[10,0,0,0],
                   [10,0,0,0],
                   [10,0,0,0],
                   [0,10,0,0],
                   [0,10,0,0],
                   [0,0,0,0],
                   [0,0,0,0],
                   [0,0,0,0]],dtype=torch.float32)
wk = torch.tensor([[2,0,0,0],
                   [2,0,0,0],
                   [2,0,0,0],
                   [0,2,0,0],
                   [0,2,0,0],
                   [0,0,0,0],
                   [0,0,0,0],
                   [0,0,0,0]],dtype=torch.float32)
wv = torch.tensor([[1,0,0,0],
                   [0,1,0,0],
                   [0,0,1,0],
                   [0,0,0,1],
                   [0,0,0,1],
                   [0,0,0,0],
                   [0,0,0,0],
                   [0,0,0,0]],dtype=torch.float32)

input_embeddings.shape,wq.shape,wk.shape,wv.shape

(torch.Size([5, 8]),
 torch.Size([8, 4]),
 torch.Size([8, 4]),
 torch.Size([8, 4]))

In [31]:
k = input_embeddings@wk
q = input_embeddings@wq
v = input_embeddings@wv
print("K",k)
print("Q",q)
print("v",v)

K tensor([[2., 0., 0., 0.],
        [2., 0., 0., 0.],
        [2., 0., 0., 0.],
        [0., 2., 0., 0.],
        [0., 2., 0., 0.]])
Q tensor([[10.,  0.,  0.,  0.],
        [10.,  0.,  0.,  0.],
        [10.,  0.,  0.,  0.],
        [ 0., 10.,  0.,  0.],
        [ 0., 10.,  0.,  0.]])
v tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.]])


In [32]:
k_t = torch.transpose(k,0,1)
k_t

tensor([[2., 2., 2., 0., 0.],
        [0., 0., 0., 2., 2.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [33]:
scores = (q@k_t)/2
scores

tensor([[10., 10., 10.,  0.,  0.],
        [10., 10., 10.,  0.,  0.],
        [10., 10., 10.,  0.,  0.],
        [ 0.,  0.,  0., 10., 10.],
        [ 0.,  0.,  0., 10., 10.]])

In [34]:
import torch.nn.functional as F

softmax_output = F.softmax(scores, dim=1)

attention = softmax_output.round(decimals=4)

print(attention)

tensor([[0.3333, 0.3333, 0.3333, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.5000, 0.5000],
        [0.0000, 0.0000, 0.0000, 0.5000, 0.5000]])


In [35]:
output = attention@v

In [36]:
output

tensor([[0.3333, 0.3333, 0.3333, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000],
        [0.0000, 0.0000, 0.0000, 1.0000],
        [0.0000, 0.0000, 0.0000, 1.0000]])