In [2]:
import torch
import torch.nn.functional as F

x = torch.tensor([
    [1,0.5,-1,0.2],
    [0.8,-0.3,0.6,1],
    [-0.5,0.9,0.1,-0.8]
])

mha_output = torch.tensor([
    [0.72,0.28,0.21,0.4],
    [0.64,0.26,0.2,0.43],
    [0.08,0.57,0.43,0.11]
])

x.shape, mha_output.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [5]:
summ = x+mha_output
summ

tensor([[ 1.7200,  0.7800, -0.7900,  0.6000],
        [ 1.4400, -0.0400,  0.8000,  1.4300],
        [-0.4200,  1.4700,  0.5300, -0.6900]])

In [15]:
norm = torch.nn.LayerNorm(4)
norm1 = norm(summ)
norm1

tensor([[ 1.2740,  0.2258, -1.5249,  0.0251],
        [ 0.8796, -1.5651, -0.1776,  0.8631],
        [-0.7551,  1.4660,  0.3614, -1.0724]],
       grad_fn=<NativeLayerNormBackward0>)

In [19]:
ffn_w1 = torch.tensor([
    [0.5,-0.2,0.8,0.1,-0.6,0.3,0.7,-0.4],
    [0.2,0.9,-0.1,0.5,-0.3,0.6,-0.8,0.2],
    [-0.7,0.4,0.6,-0.2,0.9,-0.1,0.3,0.5],
    [0.1,-0.5,0.3,0.8,-0.4,0.7,-0.2,0.6],
    
])

ffn_b1 = torch.tensor([[0.1,-0.2,0.3,-0.1,0.2,-0.3,0.1,0.4]])

ffn_w1.shape,ffn_b1.shape

(torch.Size([4, 8]), torch.Size([1, 8]))

In [20]:
ffn1 = (norm1@ffn_w1)+ffn_b1
ffn1

tensor([[ 1.8521, -0.8741,  0.3892,  0.4654, -2.0146,  0.3877,  0.3487, -0.8118],
        [ 0.4374, -2.2871,  1.3126, -0.0686, -0.3633, -0.3533,  1.7420,  0.1642],
        [-0.3445,  1.9512, -0.5555, -0.3726,  0.9674, -0.4337, -1.2785,  0.5325]],
       grad_fn=<AddBackward0>)

In [21]:
ffn_relu = torch.nn.functional.relu(ffn1)
ffn_relu

tensor([[1.8521, 0.0000, 0.3892, 0.4654, 0.0000, 0.3877, 0.3487, 0.0000],
        [0.4374, 0.0000, 1.3126, 0.0000, 0.0000, 0.0000, 1.7420, 0.1642],
        [0.0000, 1.9512, 0.0000, 0.0000, 0.9674, 0.0000, 0.0000, 0.5325]],
       grad_fn=<ReluBackward0>)

In [23]:
ffn_w2 = torch.tensor([
    [0.8,-0.1,0.4,0.2],
    [-0.3,0.7,-0.2,0.5],
    [0.6,-0.4,0.9,-0.1],
    [0.1,0.5,-0.6,0.8],
    [-0.5,0.3,0.2,-0.7],
    [0.4,-0.2,0.7,0.1],
    [-0.1,0.6,-0.3,0.9],
    [0.7,0.2,-0.5,0.3]
])

ffn_b2 = torch.tensor([[-0.2,0.1,0.3,-0.1]])

ffn_w2.shape,ffn_b2.shape

(torch.Size([8, 4]), torch.Size([1, 4]))

In [25]:
ffn_out = (ffn_relu@ffn_w2)+ffn_b2
ffn_out

tensor([[ 1.6820,  0.1234,  1.2787,  0.9563],
        [ 0.8782,  0.6092,  1.0516,  1.4732],
        [-0.8963,  1.8625, -0.1630,  0.3582]], grad_fn=<AddBackward0>)

In [27]:
summ2 = norm1 + ffn_out
summ2

tensor([[ 2.9559,  0.3492, -0.2462,  0.9814],
        [ 1.7578, -0.9559,  0.8740,  2.3363],
        [-1.6514,  3.3286,  0.1984, -0.7142]], grad_fn=<AddBackward0>)

In [28]:
norm2 = norm(summ2)
norm2

tensor([[ 1.6156, -0.5487, -1.0431, -0.0238],
        [ 0.6062, -1.5733, -0.1036,  1.0708],
        [-1.0372,  1.6229, -0.0491, -0.5366]],
       grad_fn=<NativeLayerNormBackward0>)

In [29]:
output  = norm2
output

tensor([[ 1.6156, -0.5487, -1.0431, -0.0238],
        [ 0.6062, -1.5733, -0.1036,  1.0708],
        [-1.0372,  1.6229, -0.0491, -0.5366]],
       grad_fn=<NativeLayerNormBackward0>)