In [6]:
import torch
import torch.nn.functional as F

ht = torch.tensor([[0.5,0.8,-0.2,0.1,0.9,-0.5,0.3,0.4]],dtype=float)

wq = torch.tensor([
    [1,0,0,0],
    [0,1,0,0],
    [0,0,1,0],
    [0,0,0,1],
    [1,0,1,0],
    [0,1,0,1],
    [-1,0,1,0],
    [0,-1,0,1],
],dtype=float)

w_dkv = torch.tensor([
    [1,0],
    [0,1],
    [1,0],
    [0,1],
    [0,0],
    [0,0],
    [1,1],
    [-1,-1],
],dtype=float)

ht.shape, wq.shape , w_dkv.shape

(torch.Size([1, 8]), torch.Size([8, 4]), torch.Size([8, 2]))

In [7]:
q = ht@wq
q

tensor([[ 1.1000, -0.1000,  1.0000,  0.0000]], dtype=torch.float64)

In [8]:
c_kv = ht@w_dkv
c_kv

tensor([[0.2000, 0.8000]], dtype=torch.float64)

In [11]:
w_uk = torch.tensor([
    [1,0,1,0],
    [0,1,0,1]
],dtype=float)
w_uv = torch.tensor([
    [0,2,0,1],
    [1,0,2,0],
],dtype=float)

w_uk.shape , w_uk.shape


(torch.Size([2, 4]), torch.Size([2, 4]))

In [12]:
k = c_kv@w_uk
v = c_kv@w_uv
k,v

(tensor([[0.2000, 0.8000, 0.2000, 0.8000]], dtype=torch.float64),
 tensor([[0.8000, 0.4000, 1.6000, 0.2000]], dtype=torch.float64))

In [16]:
k_transpose= torch.transpose(k,dim0=0,dim1=1)
d_k = torch.tensor(k.shape[1])
d_k

tensor(4)

In [17]:
output = F.softmax((q@k_transpose)/torch.sqrt(d_k))@v
output

C:\Users\Parthiban\AppData\Local\Temp\ipykernel_14788\833891228.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  output = F.softmax((q@k_transpose)/torch.sqrt(d_k))@v


tensor([[0.8000, 0.4000, 1.6000, 0.2000]], dtype=torch.float64)